name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '21.2.0'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        # cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run test-pages

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_WAVE_06A9E0E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/_site" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######